Azhuro\Bundle\PageBundle\Entity\BaseBlock:
    type: mappedSuperclass
    fields:
        name:
            type: string
            column: name
            length: 255
            nullable: true
        type:
            type: string
            column: type
            length: 64
        settings:
            type: json
            column: settings
        enabled:
            type: boolean
            column: enabled
            nullable: true
            default: false
        position:
            type: integer
            column: position
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at

    manyToMany:
        pages:
            targetEntity: 'Azhuro\Bundle\PageBundle\Model\Interfaces\PageInterface'
            mappedBy: blocks

    manyToOne:
        parent:
            targetEntity: 'Azhuro\Bundle\PageBundle\Model\Interfaces\BlockInterface'
            inversedBy: children

    oneToMany:
        children:
            targetEntity: 'Azhuro\Bundle\PageBundle\Model\Interfaces\BlockInterface'
            mappedBy: parent