parameters:
    page.form.type.controller_type.class: 'Azhuro\Bundle\PageBundle\Form\Type\ControllerType'
    page.form.type.page_type.class:       'Azhuro\Bundle\PageBundle\Form\Type\PageType'

services:
    page.form.type.controller_type:
        class: '%page.form.type.controller_type.class%'
        arguments:
            - '@page.resolver.controller_resolver'
        tags:
          - { name: form.type, alias: 'controller_type' }

    page.form.type.page_type:
        class: '%page.form.type.page_type.class%'
        tags:
          - { name: form.type, alias: 'page_type' }