parameters:
    azhuro_page.form.type.controller_type.class: 'Azhuro\Bundle\PageBundle\Form\Type\ControllerType'
    azhuro_page.form.type.page_type.class:       'Azhuro\Bundle\PageBundle\Form\Type\PageType'

services:
    azhuro_page.form.type.controller_type:
        class: '%azhuro_page.form.type.controller_type.class%'
        arguments:
            - '@azhuro_page.resolver.controller_resolver'
        tags:
          - { name: form.type, alias: 'controller_type' }

    azhuro_page.form.type.page_type:
        class: '%azhuro_page.form.type.page_type.class%'
        tags:
          - { name: form.type, alias: 'page_type' }