page_page:
    resource: "@AzhuroPageBundle/Resources/config/routing/page.yml"
    prefix:   /page

page_block:
    resource: "@AzhuroPageBundle/Resources/config/routing/block.yml"
    prefix:   /block