parameters:
    azhuro_page.controller.cms_controller.class:       'Azhuro\Bundle\PageBundle\Controller\CmsController'
    azhuro_page.router.dynamic_router.class:           'Azhuro\Bundle\PageBundle\Router\DynamicRouter'
    azhuro_page.resolver.controller_resolver.class:    'Azhuro\Bundle\PageBundle\Resolver\ControllerResolver'
    azhuro_page.event_listener.mapping_listener.class: 'Azhuro\Bundle\PageBundle\EventListener\LoadORMMetadataListener'
    azhuro_page.manager.page_manager.class:            'Azhuro\Bundle\PageBundle\Manager\PageManager'
    azhuro_page.manager.block_manager.class:           'Azhuro\Bundle\PageBundle\Manager\BlockManager'
    azhuro_page.twig.extension.page_extension.class:   'Azhuro\Bundle\PageBundle\Twig\Extension\PageExtension'
    azhuro_page.twig.loader.page_twig_loader.class:    'Azhuro\Bundle\PageBundle\Twig\Loader\PageTwigLoader'
    azhuro_page.templating.helper.page_helper.class:   'Azhuro\Bundle\PageBundle\Templating\Helper\PageHelper'

services:
    azhuro_page.controller.cms_controller:
        class: '%azhuro_page.controller.cms_controller.class%'
        arguments:
            - '@twig'

    azhuro_page.router.dynamic_router:
        class: '%azhuro_page.router.dynamic_router.class%'
        arguments:
            - '@azhuro_page.manager.page_manager'

    azhuro_page.resolver.controller_resolver:
        class: '%azhuro_page.resolver.controller_resolver.class%'
        parent: 'controller_resolver'
        arguments:
            - '%kernel.bundles%'

    azhuro_page.event_listener.mapping_listener:
        class: '%azhuro_page.event_listener.mapping_listener.class%'
        arguments:
            - '%page.entity.page_class%'
            - '%page.entity.block_class%'
        tags:
            - { name: 'doctrine.event_listener', event: 'loadClassMetadata' }

    azhuro_page.manager.page_manager:
        class: '%azhuro_page.manager.page_manager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%page.entity.page_class%'

    azhuro_page.manager.block_manager:
        class: '%azhuro_page.manager.block_manager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%page.entity.block_class%'

    azhuro_page.twig.extension.page_extension:
        class: '%azhuro_page.twig.extension.page_extension.class%'
        arguments:
           - '@azhuro_page.templating.helper.page_helper'
        calls:
            - [initRuntime, ['@twig']]
        tags:
            - { name: twig.extension }

    azhuro_page.templating.helper.page_helper:
        class: '%azhuro_page.templating.helper.page_helper.class%'
        arguments:
            - '@sonata.block.templating.helper'
