azhuro_page_index:
    path:     /
    defaults: { _controller: "AzhuroPageBundle:Page:index" }
    methods:  GET

azhuro_page_show:
    path:     /{id}/show
    defaults: { _controller: "AzhuroPageBundle:Page:show" }
    methods:  GET

azhuro_page_new:
    path:     /new
    defaults: { _controller: "AzhuroPageBundle:Page:new" }
    methods:  [GET, POST]

azhuro_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "AzhuroPageBundle:Page:edit" }
    methods:  [GET, POST]

azhuro_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "AzhuroPageBundle:Page:delete" }
    methods:  DELETE